# Generated by Django 5.0.6 on 2024-05-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbvApp', '0002_passenger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
